### ISSUE TITLE
How many CVEs is it capable of checking for currently?

### ISSUE THREAD

**Issue by minanagehsalalma** [umair9747/Genzai#4]
also is this inspired by RouterSploit ?

**Comment by umair9747** [comment]
Thanks for the questions, it supports scanning around 7 CVEs for routers mostly and the other 3 entries as part of vendor-vulns.json are related to exposures or misconfigs. I plan to add several more CVEs a very soon and try to target more products and categories.

As for the routersploit question, although I am not familiar with the tool or its functionality but going by its description it looks a bit similar in the goals however Genzai aims to eliminate the problem of sending unnecessary requests to a target (which can trigger any alerts). If Genzai finds a Tenda router it will only scan it against vulnerabilities or default credentials of Tenda.
Routersploit only seems to target routers and cameras whereas Genzai has a LOT more categories than that which can be verified from the README and signatures.json!

Let me know in case you have any additional questions or feedback/suggestions! 

Happy Hacking :)

**Comment by minanagehsalalma** [comment]
I see, keep it up 🔥
